node { 
    def app
    def image = 'demo-flask'
    def jenkinsCredentials = 'docker'
    def gitRepo = "https://github.com/rockoman71/demo-flask.git"
    def container = ""
    
    stage('Get Source') {
		   git gitRepo
	  }
   
    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */
        app = docker.build(image, "-t " + image + ":${BUILD_NUMBER} --build-arg ver=${BUILD_NUMBER} ./docker")
	    
    } 

	stage('Deploy image') {
	  //   sh "docker rm \$(docker stop \$(docker ps -a -f ancestor=demo-flask:latest --format='{{.ID}}' ))"
	     container = sh "docker ps -a -f ancestor=demo-flask:latest --format='{{.ID}}'"
	     if (container != '') {
		     sh "docker rm \$(docker stop \$( container ))"
	     }		
	     sh "docker run -d -p 9090:80 demo-flask:${BUILD_NUMBER}"
	}
	
}
