node { 
    def app
    def image = 'demo-flask'
    def jenkinsCredentials = 'docker'
    def gitRepo = "https://github.com/rockoman71/demo-flask.git"
    
    stage('Get Source') {
		   git gitRepo
	  }
   
    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */
        app = docker.build(image, "--build-arg ver=${BUILD_NUMBER} ./docker")
    } 

	stage('Deploy image') {
		docker.run(image,"-d -p 9090:80 demo-flask:${BUILD_NUMBER}")
		'sh docker run -d -p 9090:80 demo-flask:${BUILD_NUMBER}'
		
	}
	
}
